### ISSUE TITLE
problems with file permissions when setting up with owncloud

### ISSUE THREAD

**Issue by arielelkin** [linuxserver/docker-libresonic#21]
My music collection is synced with ownCloud (running in a container), and I'd like libresonic to read from it, but I'm running into permissions issues. 

Libresonic is able to scan the directory, but it won't let me play the files:

![image](https://user-images.githubusercontent.com/1756909/27199087-2845b32c-51eb-11e7-8965-2297b9f82900.png)

ownCloud syncs the files to ~/streamer/owncloud_data

```
$ ls -ld streamer/owncloud_data/
drwxrwx--- 5 www-data root 4096 May 24 23:36 streamer/owncloud_data/
$
$ id www-data
uid=33(www-data) gid=33(www-data) groups=33(www-data)
```

here's my docker-compose.yml:

```
version: '3'

services:
  libresonic:
    image: linuxserver/libresonic:69
    container_name: libresonic
    restart: always
    ports:
      - 4040:4040
    volumes:
        # Directory where Libresonic will look for
        # media files (read-only):
      - "~/streamer/owncloud_data:/music:ro"
        # Directory where Libresonic will save its
        # config files:
      - "~/streamer/libresonic_config:/config"
      - "~/streamer/libresonic_playlists:/playlists"
      - "~/streamer/libresonic_podcasts:/podcasts"
     environment:
      - PGID=33
      - PUID=0

  streamer_owncloud:
    image: owncloud:9
    container_name: streamer_owncloud
    restart: always
    links:
      - streamer_db
    ports:
      - 7070:80
    volumes:
      # Directory where ownCloud will sync
      # media files: (should be the same as the
      # one where Ampache looks for media files)
      - "~/streamer/owncloud_data:/var/www/html/data"
      #Directory where ownCloud will save its config files:
      - "~/streamer/owncloud_config:/var/www/html/config"

  streamer_db:
    image: mariadb
    container_name: streamer_owncloud_db
    restart: always
    volumes:
      # Directory where ownCloud's database
      # will save its config files:
      - "~/streamer/owncloud_db_data:/var/lib"
    environment:
      MYSQL_ROOT_PASSWORD: password

```

I have tried setting different PUID and PGID, but got the same results:

```
    environment:
      - PGID=33
      - PUID=33
```

```
    environment:
      - PGID=0
      - PUID=0
```

Any thoughts?
