### ISSUE TITLE
Libresonic doesn't find new files.

### ISSUE THREAD

**Issue by jcgruenhage** [linuxserver/docker-libresonic#23]
When I copy new music into /mnt/hdd02/music/music, libresonic does find the folders, but not the files inside them. The permissions are set to 644 on the files and 755 on the folders, so libresonic should be able to read them. Deleting the container and the content of /config and then running docker-compose up -d again fixes this, but this deletes any configuration, so this is merely a workaround, not a solution.

Host OS: Fedora Server 27

The relevant part of my docker-compose.yml:
```
version: '2'
services:
        libresonic:
                image: docker.io/linuxserver/libresonic
                container_name: libresonic
                volumes:
                        - ./libresonic/config:/config:z
                        - /mnt/hdd02/music/music:/music:z
                        - /mnt/hdd02/music/playlists:/playlists:z
                        - /mnt/hdd02/music/podcasts:/podcasts:z
                        - /mnt/hdd02/media:/media:z
                environment:
                        - PGID=192
                        - PUID=192
                        - TZ=Europe/Berlin
```

Edit: I sadly forgot to save the log, so that's gone. Will append it the next time this error occurs.
